### ISSUE TITLE
Generating an up to date network graph

### ISSUE THREAD

**Issue by grinapo** [TokTok/hs-github-tools#76]
Since GitHub cannot generate fork graph / network graph for any project above a certain limit, and since Tox is definitely above this limit, there is no real way to find the most recent repos, or the repos which accumulate other repo changes; it boils down to finding *the* repo (to use for people not involved in development). 

TokTok/c-toxcore#439

**Comment by iphydf** [comment]
This is a useful idea. Thanks. In the meantime, there is an unofficial manually maintained list here: https://github.com/TokTok/toktok-stack/blob/master/tools/git-remotes#L53. I maintain this as a list of "recent contributors", and if it gets too large, I'll remove some "not so recent contributors". Having that list automatically generated would be nice indeed.
